package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1



/**
 * AcademicAchievements generated by hbm2java
 */
public class AcademicAchievements  implements java.io.Serializable {


     private AcademicAchievementsId id;
     private Achievements achievements;
     private Instructor instructor;

    public AcademicAchievements() {
    }

    public AcademicAchievements(AcademicAchievementsId id, Achievements achievements, Instructor instructor) {
       this.id = id;
       this.achievements = achievements;
       this.instructor = instructor;
    }
   
    public AcademicAchievementsId getId() {
        return this.id;
    }
    
    public void setId(AcademicAchievementsId id) {
        this.id = id;
    }
    public Achievements getAchievements() {
        return this.achievements;
    }
    
    public void setAchievements(Achievements achievements) {
        this.achievements = achievements;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }




}


