package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Achievements generated by hbm2java
 */
public class Achievements  implements java.io.Serializable {


     private int achievementId;
     private String achievement;
     private Set academicAchievementses = new HashSet(0);

    public Achievements() {
    }

	
    public Achievements(int achievementId, String achievement) {
        this.achievementId = achievementId;
        this.achievement = achievement;
    }
    public Achievements(int achievementId, String achievement, Set academicAchievementses) {
       this.achievementId = achievementId;
       this.achievement = achievement;
       this.academicAchievementses = academicAchievementses;
    }
   
    public int getAchievementId() {
        return this.achievementId;
    }
    
    public void setAchievementId(int achievementId) {
        this.achievementId = achievementId;
    }
    public String getAchievement() {
        return this.achievement;
    }
    
    public void setAchievement(String achievement) {
        this.achievement = achievement;
    }
    public Set getAcademicAchievementses() {
        return this.academicAchievementses;
    }
    
    public void setAcademicAchievementses(Set academicAchievementses) {
        this.academicAchievementses = academicAchievementses;
    }




}


