package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int adminId;
     private Byte isManager;
     private String adminEmail;
     private String firstName;
     private String middleName;
     private String lastName;
     private String country;
     private Date birthdate;
     private String gender;
     private String password;
     private String paypalEmail;
     private Set applicationses = new HashSet(0);
     private Set pointsdiscounts = new HashSet(0);

    public Admin() {
    }

	
    public Admin(int adminId, String adminEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, String password, String paypalEmail) {
        this.adminId = adminId;
        this.adminEmail = adminEmail;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.country = country;
        this.birthdate = birthdate;
        this.gender = gender;
        this.password = password;
        this.paypalEmail = paypalEmail;
    }
    public Admin(int adminId, Byte isManager, String adminEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, String password, String paypalEmail, Set applicationses, Set pointsdiscounts) {
       this.adminId = adminId;
       this.isManager = isManager;
       this.adminEmail = adminEmail;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.country = country;
       this.birthdate = birthdate;
       this.gender = gender;
       this.password = password;
       this.paypalEmail = paypalEmail;
       this.applicationses = applicationses;
       this.pointsdiscounts = pointsdiscounts;
    }
   
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }
    public Byte getIsManager() {
        return this.isManager;
    }
    
    public void setIsManager(Byte isManager) {
        this.isManager = isManager;
    }
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPaypalEmail() {
        return this.paypalEmail;
    }
    
    public void setPaypalEmail(String paypalEmail) {
        this.paypalEmail = paypalEmail;
    }
    public Set getApplicationses() {
        return this.applicationses;
    }
    
    public void setApplicationses(Set applicationses) {
        this.applicationses = applicationses;
    }
    public Set getPointsdiscounts() {
        return this.pointsdiscounts;
    }
    
    public void setPointsdiscounts(Set pointsdiscounts) {
        this.pointsdiscounts = pointsdiscounts;
    }




}


