package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Applications generated by hbm2java
 */
public class Applications  implements java.io.Serializable {


     private int applicationId;
     private Admin admin;
     private String name;
     private byte[] cv;
     private String email;
     private Date submissionDate;
     private byte reviewStatus;
     private Date approvalDate;
     private Set instructors = new HashSet(0);

    public Applications() {
    }

	
    public Applications(int applicationId, Admin admin, String name, byte[] cv, String email, Date submissionDate, byte reviewStatus) {
        this.applicationId = applicationId;
        this.admin = admin;
        this.name = name;
        this.cv = cv;
        this.email = email;
        this.submissionDate = submissionDate;
        this.reviewStatus = reviewStatus;
    }
    public Applications(int applicationId, Admin admin, String name, byte[] cv, String email, Date submissionDate, byte reviewStatus, Date approvalDate, Set instructors) {
       this.applicationId = applicationId;
       this.admin = admin;
       this.name = name;
       this.cv = cv;
       this.email = email;
       this.submissionDate = submissionDate;
       this.reviewStatus = reviewStatus;
       this.approvalDate = approvalDate;
       this.instructors = instructors;
    }
   
    public int getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(int applicationId) {
        this.applicationId = applicationId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getCv() {
        return this.cv;
    }
    
    public void setCv(byte[] cv) {
        this.cv = cv;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getSubmissionDate() {
        return this.submissionDate;
    }
    
    public void setSubmissionDate(Date submissionDate) {
        this.submissionDate = submissionDate;
    }
    public byte getReviewStatus() {
        return this.reviewStatus;
    }
    
    public void setReviewStatus(byte reviewStatus) {
        this.reviewStatus = reviewStatus;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public Set getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set instructors) {
        this.instructors = instructors;
    }




}


