package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1



/**
 * CorrectAnswers generated by hbm2java
 */
public class CorrectAnswers  implements java.io.Serializable {


     private CorrectAnswersId id;
     private QuestionChoices questionChoices;

    public CorrectAnswers() {
    }

    public CorrectAnswers(QuestionChoices questionChoices) {
       this.questionChoices = questionChoices;
    }
   
    public CorrectAnswersId getId() {
        return this.id;
    }
    
    public void setId(CorrectAnswersId id) {
        this.id = id;
    }
    public QuestionChoices getQuestionChoices() {
        return this.questionChoices;
    }
    
    public void setQuestionChoices(QuestionChoices questionChoices) {
        this.questionChoices = questionChoices;
    }




}


