package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CoursefeeshistoryId generated by hbm2java
 */
public class CoursefeeshistoryId  implements java.io.Serializable {


     private Date madeDate;
     private int courseId;

    public CoursefeeshistoryId() {
    }

    public CoursefeeshistoryId(Date madeDate, int courseId) {
       this.madeDate = madeDate;
       this.courseId = courseId;
    }
   
    public Date getMadeDate() {
        return this.madeDate;
    }
    
    public void setMadeDate(Date madeDate) {
        this.madeDate = madeDate;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoursefeeshistoryId) ) return false;
		 CoursefeeshistoryId castOther = ( CoursefeeshistoryId ) other; 
         
		 return ( (this.getMadeDate()==castOther.getMadeDate()) || ( this.getMadeDate()!=null && castOther.getMadeDate()!=null && this.getMadeDate().equals(castOther.getMadeDate()) ) )
 && (this.getCourseId()==castOther.getCourseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMadeDate() == null ? 0 : this.getMadeDate().hashCode() );
         result = 37 * result + this.getCourseId();
         return result;
   }   


}


