package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int courseId;
     private Instructor instructor;
     private String title;
     private String difficulty;
     private String description;
     private byte courseStatus;
     private short estimatedTime;
     private String coursecol;
     private Set modules = new HashSet(0);
     private Set coursefeeshistories = new HashSet(0);
     private Set enrollments = new HashSet(0);
     private Set categorieses = new HashSet(0);
     private Set questionsCreateds = new HashSet(0);

    public Course() {
    }

	
    public Course(int courseId, Instructor instructor, String title, String difficulty, String description, byte courseStatus, short estimatedTime) {
        this.courseId = courseId;
        this.instructor = instructor;
        this.title = title;
        this.difficulty = difficulty;
        this.description = description;
        this.courseStatus = courseStatus;
        this.estimatedTime = estimatedTime;
    }
    public Course(int courseId, Instructor instructor, String title, String difficulty, String description, byte courseStatus, short estimatedTime, String coursecol, Set modules, Set coursefeeshistories, Set enrollments, Set categorieses, Set questionsCreateds) {
       this.courseId = courseId;
       this.instructor = instructor;
       this.title = title;
       this.difficulty = difficulty;
       this.description = description;
       this.courseStatus = courseStatus;
       this.estimatedTime = estimatedTime;
       this.coursecol = coursecol;
       this.modules = modules;
       this.coursefeeshistories = coursefeeshistories;
       this.enrollments = enrollments;
       this.categorieses = categorieses;
       this.questionsCreateds = questionsCreateds;
    }
   
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDifficulty() {
        return this.difficulty;
    }
    
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getCourseStatus() {
        return this.courseStatus;
    }
    
    public void setCourseStatus(byte courseStatus) {
        this.courseStatus = courseStatus;
    }
    public short getEstimatedTime() {
        return this.estimatedTime;
    }
    
    public void setEstimatedTime(short estimatedTime) {
        this.estimatedTime = estimatedTime;
    }
    public String getCoursecol() {
        return this.coursecol;
    }
    
    public void setCoursecol(String coursecol) {
        this.coursecol = coursecol;
    }
    public Set getModules() {
        return this.modules;
    }
    
    public void setModules(Set modules) {
        this.modules = modules;
    }
    public Set getCoursefeeshistories() {
        return this.coursefeeshistories;
    }
    
    public void setCoursefeeshistories(Set coursefeeshistories) {
        this.coursefeeshistories = coursefeeshistories;
    }
    public Set getEnrollments() {
        return this.enrollments;
    }
    
    public void setEnrollments(Set enrollments) {
        this.enrollments = enrollments;
    }
    public Set getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set categorieses) {
        this.categorieses = categorieses;
    }
    public Set getQuestionsCreateds() {
        return this.questionsCreateds;
    }
    
    public void setQuestionsCreateds(Set questionsCreateds) {
        this.questionsCreateds = questionsCreateds;
    }




}


