package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1



/**
 * Enrollment generated by hbm2java
 */
public class Enrollment  implements java.io.Serializable {


     private EnrollmentId id;
     private Course course;
     private Order order;
     private Student student;
     private byte[] certificate;
     private String comment;
     private Float overallProgress;
     private Byte rating;

    public Enrollment() {
    }

	
    public Enrollment(EnrollmentId id, Course course, Order order, Student student) {
        this.id = id;
        this.course = course;
        this.order = order;
        this.student = student;
    }
    public Enrollment(EnrollmentId id, Course course, Order order, Student student, byte[] certificate, String comment, Float overallProgress, Byte rating) {
       this.id = id;
       this.course = course;
       this.order = order;
       this.student = student;
       this.certificate = certificate;
       this.comment = comment;
       this.overallProgress = overallProgress;
       this.rating = rating;
    }
   
    public EnrollmentId getId() {
        return this.id;
    }
    
    public void setId(EnrollmentId id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public byte[] getCertificate() {
        return this.certificate;
    }
    
    public void setCertificate(byte[] certificate) {
        this.certificate = certificate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Float getOverallProgress() {
        return this.overallProgress;
    }
    
    public void setOverallProgress(Float overallProgress) {
        this.overallProgress = overallProgress;
    }
    public Byte getRating() {
        return this.rating;
    }
    
    public void setRating(Byte rating) {
        this.rating = rating;
    }




}


