package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExaminedOn generated by hbm2java
 */
public class ExaminedOn  implements java.io.Serializable {


     private ExaminedOnId id;
     private Section section;
     private Student student;
     private Date date;
     private Set questionGradeses = new HashSet(0);

    public ExaminedOn() {
    }

	
    public ExaminedOn(ExaminedOnId id, Section section, Student student, Date date) {
        this.id = id;
        this.section = section;
        this.student = student;
        this.date = date;
    }
    public ExaminedOn(ExaminedOnId id, Section section, Student student, Date date, Set questionGradeses) {
       this.id = id;
       this.section = section;
       this.student = student;
       this.date = date;
       this.questionGradeses = questionGradeses;
    }
   
    public ExaminedOnId getId() {
        return this.id;
    }
    
    public void setId(ExaminedOnId id) {
        this.id = id;
    }
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getQuestionGradeses() {
        return this.questionGradeses;
    }
    
    public void setQuestionGradeses(Set questionGradeses) {
        this.questionGradeses = questionGradeses;
    }




}


