package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private InstructorId id;
     private Applications applications;
     private String instructorEmail;
     private String firstName;
     private String middleName;
     private String lastName;
     private String country;
     private Date birthdate;
     private String gender;
     private byte accountStatus;
     private String password;
     private String businessEmail;
     private String speciality;
     private String paypalEmail;
     private Set courses = new HashSet(0);
     private Set questionsCreateds = new HashSet(0);
     private Set academicAchievementses = new HashSet(0);

    public Instructor() {
    }

	
    public Instructor(InstructorId id, Applications applications, String instructorEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, byte accountStatus, String password, String speciality, String paypalEmail) {
        this.id = id;
        this.applications = applications;
        this.instructorEmail = instructorEmail;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.country = country;
        this.birthdate = birthdate;
        this.gender = gender;
        this.accountStatus = accountStatus;
        this.password = password;
        this.speciality = speciality;
        this.paypalEmail = paypalEmail;
    }
    public Instructor(InstructorId id, Applications applications, String instructorEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, byte accountStatus, String password, String businessEmail, String speciality, String paypalEmail, Set courses, Set questionsCreateds, Set academicAchievementses) {
       this.id = id;
       this.applications = applications;
       this.instructorEmail = instructorEmail;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.country = country;
       this.birthdate = birthdate;
       this.gender = gender;
       this.accountStatus = accountStatus;
       this.password = password;
       this.businessEmail = businessEmail;
       this.speciality = speciality;
       this.paypalEmail = paypalEmail;
       this.courses = courses;
       this.questionsCreateds = questionsCreateds;
       this.academicAchievementses = academicAchievementses;
    }
   
    public InstructorId getId() {
        return this.id;
    }
    
    public void setId(InstructorId id) {
        this.id = id;
    }
    public Applications getApplications() {
        return this.applications;
    }
    
    public void setApplications(Applications applications) {
        this.applications = applications;
    }
    public String getInstructorEmail() {
        return this.instructorEmail;
    }
    
    public void setInstructorEmail(String instructorEmail) {
        this.instructorEmail = instructorEmail;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public byte getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(byte accountStatus) {
        this.accountStatus = accountStatus;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getBusinessEmail() {
        return this.businessEmail;
    }
    
    public void setBusinessEmail(String businessEmail) {
        this.businessEmail = businessEmail;
    }
    public String getSpeciality() {
        return this.speciality;
    }
    
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }
    public String getPaypalEmail() {
        return this.paypalEmail;
    }
    
    public void setPaypalEmail(String paypalEmail) {
        this.paypalEmail = paypalEmail;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getQuestionsCreateds() {
        return this.questionsCreateds;
    }
    
    public void setQuestionsCreateds(Set questionsCreateds) {
        this.questionsCreateds = questionsCreateds;
    }
    public Set getAcademicAchievementses() {
        return this.academicAchievementses;
    }
    
    public void setAcademicAchievementses(Set academicAchievementses) {
        this.academicAchievementses = academicAchievementses;
    }




}


