package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private int moduleId;
     private Course course;
     private String name;
     private byte moduleIndex;
     private String description;
     private Set sections = new HashSet(0);

    public Module() {
    }

	
    public Module(int moduleId, Course course, String name, byte moduleIndex, String description) {
        this.moduleId = moduleId;
        this.course = course;
        this.name = name;
        this.moduleIndex = moduleIndex;
        this.description = description;
    }
    public Module(int moduleId, Course course, String name, byte moduleIndex, String description, Set sections) {
       this.moduleId = moduleId;
       this.course = course;
       this.name = name;
       this.moduleIndex = moduleIndex;
       this.description = description;
       this.sections = sections;
    }
   
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getModuleIndex() {
        return this.moduleIndex;
    }
    
    public void setModuleIndex(byte moduleIndex) {
        this.moduleIndex = moduleIndex;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getSections() {
        return this.sections;
    }
    
    public void setSections(Set sections) {
        this.sections = sections;
    }




}


