package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int orderId;
     private String instructorTransactionPaypalId;
     private String adminTransactionPaypalId;
     private Date paymentDate;
     private Integer pointsSpent;
     private BigDecimal totalAmount;
     private int pointsAdded;
     private Set enrollments = new HashSet(0);

    public Order() {
    }

	
    public Order(int orderId, String instructorTransactionPaypalId, String adminTransactionPaypalId, Date paymentDate, BigDecimal totalAmount, int pointsAdded) {
        this.orderId = orderId;
        this.instructorTransactionPaypalId = instructorTransactionPaypalId;
        this.adminTransactionPaypalId = adminTransactionPaypalId;
        this.paymentDate = paymentDate;
        this.totalAmount = totalAmount;
        this.pointsAdded = pointsAdded;
    }
    public Order(int orderId, String instructorTransactionPaypalId, String adminTransactionPaypalId, Date paymentDate, Integer pointsSpent, BigDecimal totalAmount, int pointsAdded, Set enrollments) {
       this.orderId = orderId;
       this.instructorTransactionPaypalId = instructorTransactionPaypalId;
       this.adminTransactionPaypalId = adminTransactionPaypalId;
       this.paymentDate = paymentDate;
       this.pointsSpent = pointsSpent;
       this.totalAmount = totalAmount;
       this.pointsAdded = pointsAdded;
       this.enrollments = enrollments;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public String getInstructorTransactionPaypalId() {
        return this.instructorTransactionPaypalId;
    }
    
    public void setInstructorTransactionPaypalId(String instructorTransactionPaypalId) {
        this.instructorTransactionPaypalId = instructorTransactionPaypalId;
    }
    public String getAdminTransactionPaypalId() {
        return this.adminTransactionPaypalId;
    }
    
    public void setAdminTransactionPaypalId(String adminTransactionPaypalId) {
        this.adminTransactionPaypalId = adminTransactionPaypalId;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }
    public Integer getPointsSpent() {
        return this.pointsSpent;
    }
    
    public void setPointsSpent(Integer pointsSpent) {
        this.pointsSpent = pointsSpent;
    }
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public int getPointsAdded() {
        return this.pointsAdded;
    }
    
    public void setPointsAdded(int pointsAdded) {
        this.pointsAdded = pointsAdded;
    }
    public Set getEnrollments() {
        return this.enrollments;
    }
    
    public void setEnrollments(Set enrollments) {
        this.enrollments = enrollments;
    }




}


