package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1



/**
 * Pointsdiscount generated by hbm2java
 */
public class Pointsdiscount  implements java.io.Serializable {


     private int id;
     private Admin admin;
     private float discount;
     private int points;

    public Pointsdiscount() {
    }

    public Pointsdiscount(int id, Admin admin, float discount, int points) {
       this.id = id;
       this.admin = admin;
       this.discount = discount;
       this.points = points;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }
    public int getPoints() {
        return this.points;
    }
    
    public void setPoints(int points) {
        this.points = points;
    }




}


