package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * QuestionsCreated generated by hbm2java
 */
public class QuestionsCreated  implements java.io.Serializable {


     private QuestionsCreatedId id;
     private Course course;
     private Instructor instructor;
     private Section section;
     private String question;
     private float QWeight;
     private Set questionChoiceses = new HashSet(0);

    public QuestionsCreated() {
    }

	
    public QuestionsCreated(QuestionsCreatedId id, Course course, Instructor instructor, Section section, String question, float QWeight) {
        this.id = id;
        this.course = course;
        this.instructor = instructor;
        this.section = section;
        this.question = question;
        this.QWeight = QWeight;
    }
    public QuestionsCreated(QuestionsCreatedId id, Course course, Instructor instructor, Section section, String question, float QWeight, Set questionChoiceses) {
       this.id = id;
       this.course = course;
       this.instructor = instructor;
       this.section = section;
       this.question = question;
       this.QWeight = QWeight;
       this.questionChoiceses = questionChoiceses;
    }
   
    public QuestionsCreatedId getId() {
        return this.id;
    }
    
    public void setId(QuestionsCreatedId id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public float getQWeight() {
        return this.QWeight;
    }
    
    public void setQWeight(float QWeight) {
        this.QWeight = QWeight;
    }
    public Set getQuestionChoiceses() {
        return this.questionChoiceses;
    }
    
    public void setQuestionChoiceses(Set questionChoiceses) {
        this.questionChoiceses = questionChoiceses;
    }




}


