package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1



/**
 * QuestionsCreatedId generated by hbm2java
 */
public class QuestionsCreatedId  implements java.io.Serializable {


     private short questionIndex;
     private int sectionId;

    public QuestionsCreatedId() {
    }

    public QuestionsCreatedId(short questionIndex, int sectionId) {
       this.questionIndex = questionIndex;
       this.sectionId = sectionId;
    }
   
    public short getQuestionIndex() {
        return this.questionIndex;
    }
    
    public void setQuestionIndex(short questionIndex) {
        this.questionIndex = questionIndex;
    }
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionsCreatedId) ) return false;
		 QuestionsCreatedId castOther = ( QuestionsCreatedId ) other; 
         
		 return (this.getQuestionIndex()==castOther.getQuestionIndex())
 && (this.getSectionId()==castOther.getSectionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQuestionIndex();
         result = 37 * result + this.getSectionId();
         return result;
   }   


}


