package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * QuestionChoices generated by hbm2java
 */
public class QuestionChoices  implements java.io.Serializable {


     private QuestionChoicesId id;
     private QuestionsCreated questionsCreated;
     private String choice;
     private Set questionGradeses = new HashSet(0);
     private CorrectAnswers correctAnswers;

    public QuestionChoices() {
    }

	
    public QuestionChoices(QuestionChoicesId id, QuestionsCreated questionsCreated, String choice) {
        this.id = id;
        this.questionsCreated = questionsCreated;
        this.choice = choice;
    }
    public QuestionChoices(QuestionChoicesId id, QuestionsCreated questionsCreated, String choice, Set questionGradeses, CorrectAnswers correctAnswers) {
       this.id = id;
       this.questionsCreated = questionsCreated;
       this.choice = choice;
       this.questionGradeses = questionGradeses;
       this.correctAnswers = correctAnswers;
    }
   
    public QuestionChoicesId getId() {
        return this.id;
    }
    
    public void setId(QuestionChoicesId id) {
        this.id = id;
    }
    public QuestionsCreated getQuestionsCreated() {
        return this.questionsCreated;
    }
    
    public void setQuestionsCreated(QuestionsCreated questionsCreated) {
        this.questionsCreated = questionsCreated;
    }
    public String getChoice() {
        return this.choice;
    }
    
    public void setChoice(String choice) {
        this.choice = choice;
    }
    public Set getQuestionGradeses() {
        return this.questionGradeses;
    }
    
    public void setQuestionGradeses(Set questionGradeses) {
        this.questionGradeses = questionGradeses;
    }
    public CorrectAnswers getCorrectAnswers() {
        return this.correctAnswers;
    }
    
    public void setCorrectAnswers(CorrectAnswers correctAnswers) {
        this.correctAnswers = correctAnswers;
    }




}


