package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1



/**
 * Sectiontypes generated by hbm2java
 */
public class Sectiontypes  implements java.io.Serializable {


     private int typeId;
     private Section section;
     private String type;
     private byte[] video;
     private String articleContent;
     private Float examWeight;

    public Sectiontypes() {
    }

	
    public Sectiontypes(int typeId, Section section, String type) {
        this.typeId = typeId;
        this.section = section;
        this.type = type;
    }
    public Sectiontypes(int typeId, Section section, String type, byte[] video, String articleContent, Float examWeight) {
       this.typeId = typeId;
       this.section = section;
       this.type = type;
       this.video = video;
       this.articleContent = articleContent;
       this.examWeight = examWeight;
    }
   
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public byte[] getVideo() {
        return this.video;
    }
    
    public void setVideo(byte[] video) {
        this.video = video;
    }
    public String getArticleContent() {
        return this.articleContent;
    }
    
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }
    public Float getExamWeight() {
        return this.examWeight;
    }
    
    public void setExamWeight(Float examWeight) {
        this.examWeight = examWeight;
    }




}


