package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
public class Section  implements java.io.Serializable {


     private int sectionId;
     private Module module;
     private byte sectionIndex;
     private String title;
     private Set examinedOns = new HashSet(0);
     private Set questionsCreateds = new HashSet(0);
     private Set sectiontypeses = new HashSet(0);

    public Section() {
    }

	
    public Section(int sectionId, Module module, byte sectionIndex, String title) {
        this.sectionId = sectionId;
        this.module = module;
        this.sectionIndex = sectionIndex;
        this.title = title;
    }
    public Section(int sectionId, Module module, byte sectionIndex, String title, Set examinedOns, Set questionsCreateds, Set sectiontypeses) {
       this.sectionId = sectionId;
       this.module = module;
       this.sectionIndex = sectionIndex;
       this.title = title;
       this.examinedOns = examinedOns;
       this.questionsCreateds = questionsCreateds;
       this.sectiontypeses = sectiontypeses;
    }
   
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    public byte getSectionIndex() {
        return this.sectionIndex;
    }
    
    public void setSectionIndex(byte sectionIndex) {
        this.sectionIndex = sectionIndex;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getExaminedOns() {
        return this.examinedOns;
    }
    
    public void setExaminedOns(Set examinedOns) {
        this.examinedOns = examinedOns;
    }
    public Set getQuestionsCreateds() {
        return this.questionsCreateds;
    }
    
    public void setQuestionsCreateds(Set questionsCreateds) {
        this.questionsCreateds = questionsCreateds;
    }
    public Set getSectiontypeses() {
        return this.sectiontypeses;
    }
    
    public void setSectiontypeses(Set sectiontypeses) {
        this.sectiontypeses = sectiontypeses;
    }




}


