package com.elearning.www._1_4_json_entities;
// Generated Apr 26, 2025 12:43:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int studentId;
     private String studentEmail;
     private String firstName;
     private String middleName;
     private String lastName;
     private String country;
     private Date birthdate;
     private String gender;
     private byte accountStatus;
     private String password;
     private Integer currentPoints;
     private Set enrollments = new HashSet(0);
     private Set categorieses = new HashSet(0);
     private Set examinedOns = new HashSet(0);

    public Student() {
    }

	
    public Student(int studentId, String studentEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, byte accountStatus, String password) {
        this.studentId = studentId;
        this.studentEmail = studentEmail;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.country = country;
        this.birthdate = birthdate;
        this.gender = gender;
        this.accountStatus = accountStatus;
        this.password = password;
    }
    public Student(int studentId, String studentEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, byte accountStatus, String password, Integer currentPoints, Set enrollments, Set categorieses, Set examinedOns) {
       this.studentId = studentId;
       this.studentEmail = studentEmail;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.country = country;
       this.birthdate = birthdate;
       this.gender = gender;
       this.accountStatus = accountStatus;
       this.password = password;
       this.currentPoints = currentPoints;
       this.enrollments = enrollments;
       this.categorieses = categorieses;
       this.examinedOns = examinedOns;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getStudentEmail() {
        return this.studentEmail;
    }
    
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public byte getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(byte accountStatus) {
        this.accountStatus = accountStatus;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getCurrentPoints() {
        return this.currentPoints;
    }
    
    public void setCurrentPoints(Integer currentPoints) {
        this.currentPoints = currentPoints;
    }
    public Set getEnrollments() {
        return this.enrollments;
    }
    
    public void setEnrollments(Set enrollments) {
        this.enrollments = enrollments;
    }
    public Set getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set categorieses) {
        this.categorieses = categorieses;
    }
    public Set getExaminedOns() {
        return this.examinedOns;
    }
    
    public void setExaminedOns(Set examinedOns) {
        this.examinedOns = examinedOns;
    }




}


