package com.modern.www._1_2_MySql_DB_entities;
// Generated May 25, 2021 8:15:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentCourses generated by hbm2java
 */
@Entity
@Table(name="student_courses"
    ,catalog="world"
)
public class StudentCourses  implements java.io.Serializable {


     private StudentCoursesId id;
     private Courses courses;
     private Student student;
     private Date datetime;

    public StudentCourses() {
    }

	
    public StudentCourses(StudentCoursesId id, Courses courses, Student student) {
        this.id = id;
        this.courses = courses;
        this.student = student;
    }
    public StudentCourses(StudentCoursesId id, Courses courses, Student student, Date datetime) {
       this.id = id;
       this.courses = courses;
       this.student = student;
       this.datetime = datetime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="studentId", column=@Column(name="student_id", nullable=false) ), 
        @AttributeOverride(name="courseCode", column=@Column(name="course_code", nullable=false, length=45) ) } )
    public StudentCoursesId getId() {
        return this.id;
    }
    
    public void setId(StudentCoursesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="course_code", nullable=false, insertable=false, updatable=false)
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="student_id", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datetime", length=10)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


