package com.modern.www._1_2_MySql_DB_entities;
// Generated May 25, 2021 8:15:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="world"
)
public class Student  implements java.io.Serializable {


     private int studentId;
     private String studentName;
     private Integer studentAge;
     private Set<StudentCourses> studentCourseses = new HashSet<StudentCourses>(0);

    public Student() {
    }

	
    public Student(int studentId) {
        this.studentId = studentId;
    }
    public Student(int studentId, String studentName, Integer studentAge, Set<StudentCourses> studentCourseses) {
       this.studentId = studentId;
       this.studentName = studentName;
       this.studentAge = studentAge;
       this.studentCourseses = studentCourseses;
    }
   
     @Id 

    
    @Column(name="student_id", unique=true, nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="student_name", length=100)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    
    @Column(name="student_age")
    public Integer getStudentAge() {
        return this.studentAge;
    }
    
    public void setStudentAge(Integer studentAge) {
        this.studentAge = studentAge;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="student")
    public Set<StudentCourses> getStudentCourseses() {
        return this.studentCourseses;
    }
    
    public void setStudentCourseses(Set<StudentCourses> studentCourseses) {
        this.studentCourseses = studentCourseses;
    }




}


