package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcademicAchievementsId generated by hbm2java
 */
@Embeddable
public class AcademicAchievementsId  implements java.io.Serializable {


     private int achievementId;
     private int instructorId;
     private Integer applicationId;

    public AcademicAchievementsId() {
    }

	
    public AcademicAchievementsId(int achievementId, int instructorId) {
        this.achievementId = achievementId;
        this.instructorId = instructorId;
    }
    public AcademicAchievementsId(int achievementId, int instructorId, Integer applicationId) {
       this.achievementId = achievementId;
       this.instructorId = instructorId;
       this.applicationId = applicationId;
    }
   


    @Column(name="achievement_id", nullable=false)
    public int getAchievementId() {
        return this.achievementId;
    }
    
    public void setAchievementId(int achievementId) {
        this.achievementId = achievementId;
    }


    @Column(name="instructor_id", nullable=false)
    public int getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(int instructorId) {
        this.instructorId = instructorId;
    }


    @Column(name="application_id")
    public Integer getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcademicAchievementsId) ) return false;
		 AcademicAchievementsId castOther = ( AcademicAchievementsId ) other; 
         
		 return (this.getAchievementId()==castOther.getAchievementId())
 && (this.getInstructorId()==castOther.getInstructorId())
 && ( (this.getApplicationId()==castOther.getApplicationId()) || ( this.getApplicationId()!=null && castOther.getApplicationId()!=null && this.getApplicationId().equals(castOther.getApplicationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAchievementId();
         result = 37 * result + this.getInstructorId();
         result = 37 * result + ( getApplicationId() == null ? 0 : this.getApplicationId().hashCode() );
         return result;
   }   


}


