package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Achievements generated by hbm2java
 */
@Entity
@Table(name="achievements"
    ,catalog="elearning"
    , uniqueConstraints = @UniqueConstraint(columnNames="achievement") 
)
public class Achievements  implements java.io.Serializable {


     private int achievementId;
     private String achievement;
     private Set<AcademicAchievements> academicAchievementses = new HashSet<AcademicAchievements>(0);

    public Achievements() {
    }

	
    public Achievements(int achievementId, String achievement) {
        this.achievementId = achievementId;
        this.achievement = achievement;
    }
    public Achievements(int achievementId, String achievement, Set<AcademicAchievements> academicAchievementses) {
       this.achievementId = achievementId;
       this.achievement = achievement;
       this.academicAchievementses = academicAchievementses;
    }
   
     @Id 

    
    @Column(name="achievement_id", unique=true, nullable=false)
    public int getAchievementId() {
        return this.achievementId;
    }
    
    public void setAchievementId(int achievementId) {
        this.achievementId = achievementId;
    }

    
    @Column(name="achievement", unique=true, nullable=false, length=120)
    public String getAchievement() {
        return this.achievement;
    }
    
    public void setAchievement(String achievement) {
        this.achievement = achievement;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achievements")
    public Set<AcademicAchievements> getAcademicAchievementses() {
        return this.academicAchievementses;
    }
    
    public void setAcademicAchievementses(Set<AcademicAchievements> academicAchievementses) {
        this.academicAchievementses = academicAchievementses;
    }




}


