package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="elearning"
    , uniqueConstraints = {@UniqueConstraint(columnNames="admin_email"), @UniqueConstraint(columnNames="paypal_email")} 
)
public class Admin  implements java.io.Serializable {


     private int adminId;
     private Byte isManager;
     private String adminEmail;
     private String firstName;
     private String middleName;
     private String lastName;
     private String country;
     private Date birthdate;
     private String gender;
     private String password;
     private String paypalEmail;
     private Set<Applications> applicationses = new HashSet<Applications>(0);
     private Set<Pointsdiscount> pointsdiscounts = new HashSet<Pointsdiscount>(0);

    public Admin() {
    }

	
    public Admin(int adminId, String adminEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, String password, String paypalEmail) {
        this.adminId = adminId;
        this.adminEmail = adminEmail;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.country = country;
        this.birthdate = birthdate;
        this.gender = gender;
        this.password = password;
        this.paypalEmail = paypalEmail;
    }
    public Admin(int adminId, Byte isManager, String adminEmail, String firstName, String middleName, String lastName, String country, Date birthdate, String gender, String password, String paypalEmail, Set<Applications> applicationses, Set<Pointsdiscount> pointsdiscounts) {
       this.adminId = adminId;
       this.isManager = isManager;
       this.adminEmail = adminEmail;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.country = country;
       this.birthdate = birthdate;
       this.gender = gender;
       this.password = password;
       this.paypalEmail = paypalEmail;
       this.applicationses = applicationses;
       this.pointsdiscounts = pointsdiscounts;
    }
   
     @Id 

    
    @Column(name="admin_id", unique=true, nullable=false)
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="isManager")
    public Byte getIsManager() {
        return this.isManager;
    }
    
    public void setIsManager(Byte isManager) {
        this.isManager = isManager;
    }

    
    @Column(name="admin_email", unique=true, nullable=false, length=120)
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name", nullable=false)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="country", nullable=false)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", nullable=false, length=10)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="gender", nullable=false, length=6)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="password", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="paypal_email", unique=true, nullable=false, length=120)
    public String getPaypalEmail() {
        return this.paypalEmail;
    }
    
    public void setPaypalEmail(String paypalEmail) {
        this.paypalEmail = paypalEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Applications> getApplicationses() {
        return this.applicationses;
    }
    
    public void setApplicationses(Set<Applications> applicationses) {
        this.applicationses = applicationses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Pointsdiscount> getPointsdiscounts() {
        return this.pointsdiscounts;
    }
    
    public void setPointsdiscounts(Set<Pointsdiscount> pointsdiscounts) {
        this.pointsdiscounts = pointsdiscounts;
    }




}


