package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Applications generated by hbm2java
 */
@Entity
@Table(name="applications"
    ,catalog="elearning"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Applications  implements java.io.Serializable {


     private int applicationId;
     private Admin admin;
     private String name;
     private byte[] cv;
     private String email;
     private Date submissionDate;
     private byte reviewStatus;
     private Date approvalDate;
     private Set<Instructor> instructors = new HashSet<Instructor>(0);

    public Applications() {
    }

	
    public Applications(int applicationId, Admin admin, String name, byte[] cv, String email, Date submissionDate, byte reviewStatus) {
        this.applicationId = applicationId;
        this.admin = admin;
        this.name = name;
        this.cv = cv;
        this.email = email;
        this.submissionDate = submissionDate;
        this.reviewStatus = reviewStatus;
    }
    public Applications(int applicationId, Admin admin, String name, byte[] cv, String email, Date submissionDate, byte reviewStatus, Date approvalDate, Set<Instructor> instructors) {
       this.applicationId = applicationId;
       this.admin = admin;
       this.name = name;
       this.cv = cv;
       this.email = email;
       this.submissionDate = submissionDate;
       this.reviewStatus = reviewStatus;
       this.approvalDate = approvalDate;
       this.instructors = instructors;
    }
   
     @Id 

    
    @Column(name="application_id", unique=true, nullable=false)
    public int getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(int applicationId) {
        this.applicationId = applicationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="cv", nullable=false)
    public byte[] getCv() {
        return this.cv;
    }
    
    public void setCv(byte[] cv) {
        this.cv = cv;
    }

    
    @Column(name="email", unique=true, nullable=false, length=120)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="submission_date", nullable=false, length=10)
    public Date getSubmissionDate() {
        return this.submissionDate;
    }
    
    public void setSubmissionDate(Date submissionDate) {
        this.submissionDate = submissionDate;
    }

    
    @Column(name="review_status", nullable=false)
    public byte getReviewStatus() {
        return this.reviewStatus;
    }
    
    public void setReviewStatus(byte reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="approval_date", length=10)
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="applications")
    public Set<Instructor> getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set<Instructor> instructors) {
        this.instructors = instructors;
    }




}


