package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="categories"
    ,catalog="elearning"
)
public class Categories  implements java.io.Serializable {


     private byte categoryId;
     private String type;
     private String name;
     private Set<Student> students = new HashSet<Student>(0);
     private Set<Course> courses = new HashSet<Course>(0);

    public Categories() {
    }

	
    public Categories(byte categoryId, String type, String name) {
        this.categoryId = categoryId;
        this.type = type;
        this.name = name;
    }
    public Categories(byte categoryId, String type, String name, Set<Student> students, Set<Course> courses) {
       this.categoryId = categoryId;
       this.type = type;
       this.name = name;
       this.students = students;
       this.courses = courses;
    }
   
     @Id 

    
    @Column(name="category_id", unique=true, nullable=false)
    public byte getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(byte categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="interests", catalog="elearning", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="student_id", nullable=false, updatable=false) })
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="categorieses")
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


