package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * CorrectAnswers generated by hbm2java
 */
@Entity
@Table(name="correct_answers"
    ,catalog="elearning"
)
public class CorrectAnswers  implements java.io.Serializable {


     private CorrectAnswersId id;
     private QuestionChoices questionChoices;

    public CorrectAnswers() {
    }

    public CorrectAnswers(QuestionChoices questionChoices) {
       this.questionChoices = questionChoices;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="choiceIndex", column=@Column(name="choice_index", nullable=false) ), 
        @AttributeOverride(name="questionIndex", column=@Column(name="question_index", nullable=false) ), 
        @AttributeOverride(name="sectionId", column=@Column(name="section_id", nullable=false) ) } )
    public CorrectAnswersId getId() {
        return this.id;
    }
    
    public void setId(CorrectAnswersId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public QuestionChoices getQuestionChoices() {
        return this.questionChoices;
    }
    
    public void setQuestionChoices(QuestionChoices questionChoices) {
        this.questionChoices = questionChoices;
    }




}


