package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coursefeeshistory generated by hbm2java
 */
@Entity
@Table(name="coursefeeshistory"
    ,catalog="elearning"
)
public class Coursefeeshistory  implements java.io.Serializable {


     private CoursefeeshistoryId id;
     private Course course;
     private BigDecimal fees;

    public Coursefeeshistory() {
    }

	
    public Coursefeeshistory(CoursefeeshistoryId id, Course course) {
        this.id = id;
        this.course = course;
    }
    public Coursefeeshistory(CoursefeeshistoryId id, Course course, BigDecimal fees) {
       this.id = id;
       this.course = course;
       this.fees = fees;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="madeDate", column=@Column(name="made_date", nullable=false, length=19) ), 
        @AttributeOverride(name="courseId", column=@Column(name="course_id", nullable=false) ) } )
    public CoursefeeshistoryId getId() {
        return this.id;
    }
    
    public void setId(CoursefeeshistoryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false, insertable=false, updatable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="fees", precision=9)
    public BigDecimal getFees() {
        return this.fees;
    }
    
    public void setFees(BigDecimal fees) {
        this.fees = fees;
    }




}


