package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExaminedOn generated by hbm2java
 */
@Entity
@Table(name="examined_on"
    ,catalog="elearning"
)
public class ExaminedOn  implements java.io.Serializable {


     private ExaminedOnId id;
     private Section section;
     private Student student;
     private Date date;
     private Set<QuestionGrades> questionGradeses = new HashSet<QuestionGrades>(0);

    public ExaminedOn() {
    }

	
    public ExaminedOn(ExaminedOnId id, Section section, Student student, Date date) {
        this.id = id;
        this.section = section;
        this.student = student;
        this.date = date;
    }
    public ExaminedOn(ExaminedOnId id, Section section, Student student, Date date, Set<QuestionGrades> questionGradeses) {
       this.id = id;
       this.section = section;
       this.student = student;
       this.date = date;
       this.questionGradeses = questionGradeses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="attemptNo", column=@Column(name="attempt_no", nullable=false) ), 
        @AttributeOverride(name="sectionId", column=@Column(name="section_id", nullable=false) ), 
        @AttributeOverride(name="studentId", column=@Column(name="student_id", nullable=false) ) } )
    public ExaminedOnId getId() {
        return this.id;
    }
    
    public void setId(ExaminedOnId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="section_id", nullable=false, insertable=false, updatable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="examinedOn")
    public Set<QuestionGrades> getQuestionGradeses() {
        return this.questionGradeses;
    }
    
    public void setQuestionGradeses(Set<QuestionGrades> questionGradeses) {
        this.questionGradeses = questionGradeses;
    }




}


