package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="module"
    ,catalog="elearning"
)
public class Module  implements java.io.Serializable {


     private int moduleId;
     private Course course;
     private String name;
     private byte moduleIndex;
     private String description;
     private Set<Section> sections = new HashSet<Section>(0);

    public Module() {
    }

	
    public Module(int moduleId, Course course, String name, byte moduleIndex, String description) {
        this.moduleId = moduleId;
        this.course = course;
        this.name = name;
        this.moduleIndex = moduleIndex;
        this.description = description;
    }
    public Module(int moduleId, Course course, String name, byte moduleIndex, String description, Set<Section> sections) {
       this.moduleId = moduleId;
       this.course = course;
       this.name = name;
       this.moduleIndex = moduleIndex;
       this.description = description;
       this.sections = sections;
    }
   
     @Id 

    
    @Column(name="module_id", unique=true, nullable=false)
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="module_index", nullable=false)
    public byte getModuleIndex() {
        return this.moduleIndex;
    }
    
    public void setModuleIndex(byte moduleIndex) {
        this.moduleIndex = moduleIndex;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<Section> getSections() {
        return this.sections;
    }
    
    public void setSections(Set<Section> sections) {
        this.sections = sections;
    }




}


