package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pointsdiscount generated by hbm2java
 */
@Entity
@Table(name="pointsdiscount"
    ,catalog="elearning"
    , uniqueConstraints = {@UniqueConstraint(columnNames="discount"), @UniqueConstraint(columnNames="points")} 
)
public class Pointsdiscount  implements java.io.Serializable {


     private int id;
     private Admin admin;
     private float discount;
     private int points;

    public Pointsdiscount() {
    }

    public Pointsdiscount(int id, Admin admin, float discount, int points) {
       this.id = id;
       this.admin = admin;
       this.discount = discount;
       this.points = points;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="discount", unique=true, nullable=false, precision=5)
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }

    
    @Column(name="points", unique=true, nullable=false)
    public int getPoints() {
        return this.points;
    }
    
    public void setPoints(int points) {
        this.points = points;
    }




}


