package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * QuestionChoices generated by hbm2java
 */
@Entity
@Table(name="question_choices"
    ,catalog="elearning"
)
public class QuestionChoices  implements java.io.Serializable {


     private QuestionChoicesId id;
     private QuestionsCreated questionsCreated;
     private String choice;
     private Set<QuestionGrades> questionGradeses = new HashSet<QuestionGrades>(0);
     private CorrectAnswers correctAnswers;

    public QuestionChoices() {
    }

	
    public QuestionChoices(QuestionChoicesId id, QuestionsCreated questionsCreated, String choice) {
        this.id = id;
        this.questionsCreated = questionsCreated;
        this.choice = choice;
    }
    public QuestionChoices(QuestionChoicesId id, QuestionsCreated questionsCreated, String choice, Set<QuestionGrades> questionGradeses, CorrectAnswers correctAnswers) {
       this.id = id;
       this.questionsCreated = questionsCreated;
       this.choice = choice;
       this.questionGradeses = questionGradeses;
       this.correctAnswers = correctAnswers;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="choiceIndex", column=@Column(name="choice_index", nullable=false) ), 
        @AttributeOverride(name="questionIndex", column=@Column(name="question_index", nullable=false) ), 
        @AttributeOverride(name="sectionId", column=@Column(name="section_id", nullable=false) ) } )
    public QuestionChoicesId getId() {
        return this.id;
    }
    
    public void setId(QuestionChoicesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="question_index", referencedColumnName="question_index", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="section_id", referencedColumnName="section_id", nullable=false, insertable=false, updatable=false) } )
    public QuestionsCreated getQuestionsCreated() {
        return this.questionsCreated;
    }
    
    public void setQuestionsCreated(QuestionsCreated questionsCreated) {
        this.questionsCreated = questionsCreated;
    }

    
    @Column(name="choice", nullable=false, length=65535)
    public String getChoice() {
        return this.choice;
    }
    
    public void setChoice(String choice) {
        this.choice = choice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionChoices")
    public Set<QuestionGrades> getQuestionGradeses() {
        return this.questionGradeses;
    }
    
    public void setQuestionGradeses(Set<QuestionGrades> questionGradeses) {
        this.questionGradeses = questionGradeses;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="questionChoices")
    public CorrectAnswers getCorrectAnswers() {
        return this.correctAnswers;
    }
    
    public void setCorrectAnswers(CorrectAnswers correctAnswers) {
        this.correctAnswers = correctAnswers;
    }




}


