package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionGradesId generated by hbm2java
 */
@Embeddable
public class QuestionGradesId  implements java.io.Serializable {


     private int sectionId;
     private int studentId;
     private short questionIndex;
     private byte attemptNo;

    public QuestionGradesId() {
    }

    public QuestionGradesId(int sectionId, int studentId, short questionIndex, byte attemptNo) {
       this.sectionId = sectionId;
       this.studentId = studentId;
       this.questionIndex = questionIndex;
       this.attemptNo = attemptNo;
    }
   


    @Column(name="section_id", nullable=false)
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }


    @Column(name="student_id", nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }


    @Column(name="question_index", nullable=false)
    public short getQuestionIndex() {
        return this.questionIndex;
    }
    
    public void setQuestionIndex(short questionIndex) {
        this.questionIndex = questionIndex;
    }


    @Column(name="attempt_no", nullable=false)
    public byte getAttemptNo() {
        return this.attemptNo;
    }
    
    public void setAttemptNo(byte attemptNo) {
        this.attemptNo = attemptNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionGradesId) ) return false;
		 QuestionGradesId castOther = ( QuestionGradesId ) other; 
         
		 return (this.getSectionId()==castOther.getSectionId())
 && (this.getStudentId()==castOther.getStudentId())
 && (this.getQuestionIndex()==castOther.getQuestionIndex())
 && (this.getAttemptNo()==castOther.getAttemptNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSectionId();
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getQuestionIndex();
         result = 37 * result + this.getAttemptNo();
         return result;
   }   


}


