package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionChoicesId generated by hbm2java
 */
@Embeddable
public class QuestionChoicesId  implements java.io.Serializable {


     private byte choiceIndex;
     private short questionIndex;
     private int sectionId;

    public QuestionChoicesId() {
    }

    public QuestionChoicesId(byte choiceIndex, short questionIndex, int sectionId) {
       this.choiceIndex = choiceIndex;
       this.questionIndex = questionIndex;
       this.sectionId = sectionId;
    }
   


    @Column(name="choice_index", nullable=false)
    public byte getChoiceIndex() {
        return this.choiceIndex;
    }
    
    public void setChoiceIndex(byte choiceIndex) {
        this.choiceIndex = choiceIndex;
    }


    @Column(name="question_index", nullable=false)
    public short getQuestionIndex() {
        return this.questionIndex;
    }
    
    public void setQuestionIndex(short questionIndex) {
        this.questionIndex = questionIndex;
    }


    @Column(name="section_id", nullable=false)
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionChoicesId) ) return false;
		 QuestionChoicesId castOther = ( QuestionChoicesId ) other; 
         
		 return (this.getChoiceIndex()==castOther.getChoiceIndex())
 && (this.getQuestionIndex()==castOther.getQuestionIndex())
 && (this.getSectionId()==castOther.getSectionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getChoiceIndex();
         result = 37 * result + this.getQuestionIndex();
         result = 37 * result + this.getSectionId();
         return result;
   }   


}


