package com.elearning.www._1_2_MySql_DB_entities;
// Generated Apr 26, 2025 12:43:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sectiontypes generated by hbm2java
 */
@Entity
@Table(name="sectiontypes"
    ,catalog="elearning"
)
public class Sectiontypes  implements java.io.Serializable {


     private int typeId;
     private Section section;
     private String type;
     private byte[] video;
     private String articleContent;
     private Float examWeight;

    public Sectiontypes() {
    }

	
    public Sectiontypes(int typeId, Section section, String type) {
        this.typeId = typeId;
        this.section = section;
        this.type = type;
    }
    public Sectiontypes(int typeId, Section section, String type, byte[] video, String articleContent, Float examWeight) {
       this.typeId = typeId;
       this.section = section;
       this.type = type;
       this.video = video;
       this.articleContent = articleContent;
       this.examWeight = examWeight;
    }
   
     @Id 

    
    @Column(name="type_id", unique=true, nullable=false)
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="section_id", nullable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }

    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="video")
    public byte[] getVideo() {
        return this.video;
    }
    
    public void setVideo(byte[] video) {
        this.video = video;
    }

    
    @Column(name="article_content")
    public String getArticleContent() {
        return this.articleContent;
    }
    
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }

    
    @Column(name="exam_weight", precision=5)
    public Float getExamWeight() {
        return this.examWeight;
    }
    
    public void setExamWeight(Float examWeight) {
        this.examWeight = examWeight;
    }




}


